---

##
# This file is part of the `src-run/augustus-file-object-library` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
# (c) Scribe Inc      <scr@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this source code.
##

sudo     : false
language : php
php      : [ 5.6, 7.0, 7.1 ]

git:
  depth : 3

env:
  global:
    - secure: "zNCXTRGXIoBm+0vAS5f2+lV4KSfTc1Wf+VFy2bYchFX2Yg7EyjQXUEpsucT6uYoZmrHTS8MxdyJRw5R//JkxZwrxlFMQ6nJA6B4PMZxnlc6yvutZoewQqDgZh5lniZT3AC8ucFAOAd8NNEQXD3CZDvrtzO87LyAy3rjEvzbThykLqtzfs1Onh/LOZhqY3OXt6sYv/ib0H5tOULEpEvdx6xMNqvH8lcVMl33lU5ZAdUvlpkD+UBsCTIjgGkyVEzzH6NmVsWXN0JAx0lLRhpDbwUhgGmPGbSCXp7d9pcHupzmgjXLEVlCHzTiwK3uA4xGthjYyAhwToNfp78uFfIG25/GpZHmKQo8SFuuCiyctq8DlS+5FYgm0VoAXOuvxW0UuXzygNLNOOOXb076KyBM8cdTy7KznodNadM9BrnHY4pkgHyT164LEmL/I7x4GaX6zimhmcDNqkZEDibfWPY3yRzUnxGam1RuzBEj7mmT47PGthzyMiSscPKuTFfgqNlLE/GEyUuFw/JYBwPiwBUzYz8rrSJge+HsfYVz6/2RWLSn+zu0m/Nq1qQw3W6YbphLM06p08Ylbnx+A03EpuktvcMvBxnK3XLln8/gt5g7ErRuhfeT/yT3QeL3iDOAwa+DkQXcX78IIwsfEUsOwMyNkDW2ADWqssvEvOS195bRcZ4E="

install :
  - bash .bldr/bldr -b up-env -q
  - bash .bldr/bldr -b up-app -q

script :
  - bin/phpunit -vvv

after_script :
  - bash .bldr/bldr -b down-app -q
  - bash .bldr/bldr -b down-env -q

...
